name: Runs on Jupyter4NFDI

on:
  workflow_dispatch:
  schedule:
    - cron: "20 13 * * 4"

jobs:
  notebooks:
    runs-on: ubuntu-latest
    environment: jupyter4nfdi
    steps:
      - name: Run notebooks via papermill on JupyterHub
        uses: NFDI-Jupyter/ghactions/.github/actions/notebooks@main
        with:
          api_url: https://jupyter-staging.jsc.fz-juelich.de/hub/api/job
          repo: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          token: ${{ secrets.JUPYTERHUB_API_TOKEN }}
